###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "renacierr@gmail.com",
    "password": "asd12345"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "renacierr@gmail.com",
    "name": "renaja",
    "username": "renaje",
    "password": "asd12345"
}

GET http://localhost:3000/users/daa7f3a2-f941-4a9e-87c0-be747c685eea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhYTdmM2EyLWY5NDEtNGE5ZS04N2MwLWJlNzQ3YzY4NWVlYSIsImVtYWlsIjoicmVuYWNpZXJyQGdtYWlsLmNvbSIsImlhdCI6MTY4MTg3MzQyMywiZXhwIjoxNjgxODc0MzIzfQ.N2OljhVEBlqCBGTaEcEa_8P7FC9RwT35B_qu08RG7DA

###
PATCH http://localhost:3000/activation-link/8d1d88de-be9d-4bbd-9ded-37aaff838fa0

### request activation link
POST  http://localhost:3000/activation-link/generate/daa7f3a2-f941-4a9e-87c0-be747c685eea

### request token
GET http://localhost:3000/auth/token

### logout
DELETE  http://localhost:3000/auth/logout

### get newest forum
GET http://localhost:3000/forums/newest

### Create Forum
POST http://localhost:3000/forums/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0ZTFiYmJjLTMwOTktNDI3Yi04MWJmLWJhMWVlYzYzZmZiOCIsImVtYWlsIjoicmVuYWNpZXJyQGdtYWlsLmNvbSIsInJvbGUiOiJNZW1iZXIiLCJpYXQiOjE2ODIyNDAzMzgsImV4cCI6MTY4MjI0MTIzOH0.ZHgK_alDuhgoYejt6FfxhBcCb7vUMTmPlS1vyZ-oW4s

{
    "title" : "Justine",
    "description" : "Winata"
}


### Create Comment
POST http://localhost:3000/forum-comments/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0ZTFiYmJjLTMwOTktNDI3Yi04MWJmLWJhMWVlYzYzZmZiOCIsImVtYWlsIjoicmVuYWNpZXJyQGdtYWlsLmNvbSIsInJvbGUiOiJEb2N0b3IiLCJpYXQiOjE2ODIzMjk5NjksImV4cCI6MTY4MjMzMDg2OX0.dvchQy3o6Xmx7-uiUJ8GchKGFeqykat1CIqFNcpIx1Q

{
    "forumId" : "2f44b8bb-e05b-4eef-83d6-43373cee4727",
    "comment" : "Hello World"
}

### Get Forum Detail
GET http://localhost:3000/forums/get/2f44b8bb-e05b-4eef-83d6-43373cee4727
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0ZTFiYmJjLTMwOTktNDI3Yi04MWJmLWJhMWVlYzYzZmZiOCIsImVtYWlsIjoicmVuYWNpZXJyQGdtYWlsLmNvbSIsInJvbGUiOiJEb2N0b3IiLCJpYXQiOjE2ODIzMjk5NjksImV4cCI6MTY4MjMzMDg2OX0.dvchQy3o6Xmx7-uiUJ8GchKGFeqykat1CIqFNcpIx1Q


###
PATCH http://localhost:3000/users/update-profile-picture
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0ZTFiYmJjLTMwOTktNDI3Yi04MWJmLWJhMWVlYzYzZmZiOCIsImVtYWlsIjoicmVuYWNpZXJyQGdtYWlsLmNvbSIsInJvbGUiOiJEb2N0b3IiLCJpYXQiOjE2ODIzMjk5NjksImV4cCI6MTY4MjMzMDg2OX0.dvchQy3o6Xmx7-uiUJ8GchKGFeqykat1CIqFNcpIx1Q
{
    "profilePicture" : ""
}

### refetch
GET http://localhost:3000/users/fetch
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQ0ZTFiYmJjLTMwOTktNDI3Yi04MWJmLWJhMWVlYzYzZmZiOCIsImVtYWlsIjoicmVuYWNpZXJyQGdtYWlsLmNvbSIsInJvbGUiOiJEb2N0b3IiLCJpYXQiOjE2ODI0MzU2NDQsImV4cCI6MTY4MjQzNjU0NH0.PS53hHXd4Z4KVMp-hf9oEbu54Cfu9BibpGMha6HlBI4