###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "renacierr@gmail.com",
    "password": "asd12345"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "renacierr@gmail.com",
    "name": "renaja",
    "username": "renaje",
    "password": "asd12345"
}

###
GET http://localhost:3000/users/daa7f3a2-f941-4a9e-87c0-be747c685eea
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImRhYTdmM2EyLWY5NDEtNGE5ZS04N2MwLWJlNzQ3YzY4NWVlYSIsImVtYWlsIjoicmVuYWNpZXJyQGdtYWlsLmNvbSIsImlhdCI6MTY4MTg3MzQyMywiZXhwIjoxNjgxODc0MzIzfQ.N2OljhVEBlqCBGTaEcEa_8P7FC9RwT35B_qu08RG7DA

###
PATCH http://localhost:3000/activation-link/8d1d88de-be9d-4bbd-9ded-37aaff838fa0

### request activation link
POST  http://localhost:3000/activation-link/generate/daa7f3a2-f941-4a9e-87c0-be747c685eea

### request token
GET http://localhost:3000/auth/token

### logout
DELETE  http://localhost:3000/auth/logout